<Project>
  <PropertyGroup>
    <MewUIVersion>0.22.1</MewUIVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Aprillz.MewUI.Core" Version="$(MewUIVersion)" />
    <PackageVersion Include="Aprillz.MewUI.Platform.Win32" Version="$(MewUIVersion)" />
    <PackageVersion Include="Aprillz.MewUI.Backend.Direct2D" Version="$(MewUIVersion)" />
    <PackageVersion Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <PackageVersion Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>
</Project>
