"""Extracts the Fluent icons the app uses from MewUI's Gallery Icons.xaml into IconData.g.cs.

Usage: python tools/extract-icons.py   (run from repo root; needs ref/MewUI cloned)
"""
import re, pathlib

ICONS = [
    "cube_regular", "layer_regular", "storage_regular", "globe_regular", "settings_regular",
    "play_regular", "stop_regular", "delete_regular", "arrow_clockwise_regular", "arrow_download_regular",
    "window_dev_tools_regular", "text_description_regular", "folder_regular", "search_regular",
    "info_regular", "wrench_regular", "broom_regular", "add_regular", "more_regular", "copy_regular",
    "open_regular", "link_regular",
]

src = pathlib.Path("ref/MewUI/samples/MewUI.Gallery/Resources/Icons.xaml").read_text(encoding="utf-8")
paths = {m[0]: re.sub(r"\s+", " ", m[1].strip())
         for m in re.findall(r'<PathGeometry\s+x:Key="([^"]+)"[^>]*(?<!/)>\s*([\s\S]*?)\s*</PathGeometry>', src)}

def pascal(name):
    return "".join(p.capitalize() for p in name.removesuffix("_regular").split("_"))

lines = [
    "// <auto-generated> by tools/extract-icons.py from Fluent UI System Icons (MIT) via MewUI's Gallery. Do not edit.",
    "namespace WslcGui.App.Icons;",
    "",
    "internal static class IconData",
    "{",
]
for name in ICONS:
    lines.append(f'    public const string {pascal(name)} = "{paths[name]}";')
lines.append("}")
pathlib.Path("src/WslcGui.App/Icons/IconData.g.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote {len(ICONS)} icons")
